import streamlit as st
import pandas as pd
from fpdf import FPDF

# --- 1. CORE INITIALIZATION ---
ACTIVATION_KEY = "PAK-2026"

if 'authenticated' not in st.session_state: st.session_state.authenticated = False
if 'setup_complete' not in st.session_state: st.session_state.setup_complete = False
if 'data_store' not in st.session_state:
    st.session_state.data_store = {
        "Grades_Config": {},
        "A": [], # Student Performance            
        "B": [], # Teacher Experts            
        "C": [], # Efficiency Mapping            
        "School_Name": ""
    }

# --- 2. PDF ENGINE ---
class SchoolPDF(FPDF):
    def header(self):
        # Background color for header
        self.set_fill_color(230, 230, 230)
        self.set_font('Arial', 'B', 16)
        
        # Institution Name
        school_name = st.session_state.data_store.get("School_Name", "EDUCATIONAL INSTITUTION").upper()
        self.cell(0, 15, school_name, 0, 1, 'C', fill=True)
        
        # Report Title
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, "Official Performance & Efficiency Report", 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI System 2026', 0, 0, 'C')

def create_pdf(data, title):
    pdf = SchoolPDF()
    pdf.add_page()
    df = pd.DataFrame(data)
    
    # Report Section Title
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Section: {title}", 0, 1, 'L')
    pdf.ln(2)
    
    # Table Header
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(200, 220, 255)
    
    if not df.empty:
        col_width = 190 / len(df.columns)
        for col in df.columns:
            pdf.cell(col_width, 10, str(col), 1, 0, 'C', fill=True)
        pdf.ln()
        
        # Table Body
        pdf.set_font('Arial', '', 9)
        for _, row in df.iterrows():
            for val in row:
                pdf.cell(col_width, 10, str(val), 1, 0, 'C')
            pdf.ln()
            
    return pdf.output(dest='S').encode('latin-1')

# --- 3. BULK UPLOAD LOGIC ---
def handle_bulk_upload():
    st.sidebar.markdown("---")
    st.sidebar.subheader("📂 Excel Bulk Load")
    upload_type = st.sidebar.selectbox("Select Upload Type", ["Classes", "Student Performance", "Teachers"])
    uploaded_file = st.sidebar.file_uploader(f"Upload {upload_type} Excel", type=["xlsx"])

    if uploaded_file:
        try:
            df = pd.read_excel(uploaded_file)
            df.columns = [str(c).strip() for c in df.columns]
            
            if st.sidebar.button(f"Process {upload_type}"):
                if upload_type == "Classes":
                    for _, row in df.iterrows():
                        key = f"{row['Grade']}-{row['Section']}"
                        subs = [s.strip() for s in str(row['Subjects']).split(",")]
                        st.session_state.data_store["Grades_Config"][key] = subs
                    st.sidebar.success("Classes Loaded!")
                
                elif upload_type == "Student Performance":
                    for col in ['A', 'B', 'C', 'D']:
                        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
                    for _, row in df.iterrows():
                        st.session_state.data_store["A"].append({
                            "Class": str(row['Class']), "Subject": str(row['Subject']),
                            "A": int(row['A']), "B": int(row['B']), "C": int(row['C']), "D": int(row['D']),
                            "Total": int(row['A']+row['B']+row['C']+row['D'])
                        })
                    st.sidebar.success(f"Loaded {len(df)} Records!")

                elif upload_type == "Teachers":
                    for _, row in df.iterrows():
                        st.session_state.data_store["B"].append({
                            "Name": row['Name'], "Expertise": row['Expertise'], "Success": row['Success']
                        })
                    st.sidebar.success(f"Loaded {len(df)} Teachers!")
                st.rerun()
        except Exception as e:
            st.sidebar.error(f"Error processing file.")

# --- 4. UI LOGIC ---
if not st.session_state.authenticated:
    st.title("🔐 Secure Activation")
    key_input = st.text_input("Enter System Key", type="password")
    if st.button("Activate System"):
        if key_input == ACTIVATION_KEY:
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Invalid Access Key")

elif not st.session_state.setup_complete:
    handle_bulk_upload()
    st.title("⚙️ School Configuration")
    st.session_state.data_store["School_Name"] = st.text_input("School Name", st.session_state.data_store.get("School_Name", "My Institution"))
    
    st.subheader("Step 1: Define Grade, Section & Subjects")
    c1, c2 = st.columns(2)
    g_name = c1.selectbox("Grade", [f"Grade {i}" for i in range(1, 13)])
    s_name = c2.text_input("Section Name (e.g., A, B, Blue)")
    sub_input = st.text_area("Enter Subjects (separated by comma)", "Math, English, Science")
    
    if st.button("Add This Class Configuration"):
        if s_name:
            full_key = f"{g_name}-{s_name}"
            subjects = [s.strip() for s in sub_input.split(",") if s.strip()]
            st.session_state.data_store["Grades_Config"][full_key] = subjects
            st.success(f"✅ Added {full_key} successfully!")
    
    st.markdown("---")
    if st.session_state.data_store["Grades_Config"]:
        if st.button("🚀 Finalize & Go to Dashboard"):
            st.session_state.setup_complete = True
            st.rerun()

else:
    # Header display
    st.title(f"🏫 {st.session_state.data_store['School_Name']}")
    st.sidebar.title("Navigation")
    handle_bulk_upload()
    nav = st.sidebar.selectbox("Main Navigation", ["Student Performance (A)", "Teacher Experts (B)", "Efficiency Mapping (C)"])

    display_key = None 

    if nav == "Student Performance (A)":
        st.header("📊 Student Performance Records")
        display_key = "A"
        class_list = list(st.session_state.data_store["Grades_Config"].keys())
        if class_list:
            with st.expander("➕ Manual Entry"):
                sel_class = st.selectbox("Select Class", class_list)
                sel_sub = st.selectbox("Select Subject", st.session_state.data_store["Grades_Config"][sel_class])
                with st.form("a_form"):
                    c1, c2, c3, c4 = st.columns(4)
                    ga, gb, gc, gd = c1.number_input("A", 0), c2.number_input("B", 0), c3.number_input("C", 0), c4.number_input("D", 0)
                    if st.form_submit_button("Save Record"):
                        st.session_state.data_store["A"].append({
                            "Class": sel_class, "Subject": sel_sub, "A": ga, "B": gb, "C": gc, "D": gd, "Total": ga+gb+gc+gd
                        })
                        st.rerun()

    elif nav == "Teacher Experts (B)":
        st.header("👨‍🏫 Teacher Specialization")
        display_key = "B"
        all_subs = set()
        for s_list in st.session_state.data_store["Grades_Config"].values(): all_subs.update(s_list)
        
        with st.form("b_form"):
            t_name = st.text_input("Teacher Name")
            t_exp = st.selectbox("Subject Expertise", list(all_subs) if all_subs else ["N/A"])
            t_rate = st.slider("Success Rate (%)", 1, 100, 70)
            if st.form_submit_button("Register"):
                st.session_state.data_store["B"].append({"Name": t_name, "Expertise": t_exp, "Success": t_rate})
                st.rerun()

    elif nav == "Efficiency Mapping (C)":
        st.header("🎯 Efficiency Mapping & Deployment")
        display_key = "C"
        if not st.session_state.data_store["A"] or not st.session_state.data_store["B"]:
            st.warning("Ensure sections A and B are completed first.")
        else:
            options = [f"{x['Class']} | {x['Subject']}" for x in st.session_state.data_store["A"]]
            sel = st.selectbox("Analyze Class/Subject", options)
            parts = sel.split(" | ")
            matches = [t for t in st.session_state.data_store["B"] if t['Expertise'] == parts[1]]
            
            if matches:
                best_t = sorted(matches, key=lambda x: x['Success'], reverse=True)[0]
                st.info(f"💡 Recommended Faculty: **{best_t['Name']}**")
                if st.button("Confirm Allocation"):
                    st.session_state.data_store["C"].append({
                        "Institution": st.session_state.data_store["School_Name"],
                        "Class": parts[0], 
                        "Subject": parts[1], 
                        "Teacher": best_t['Name'], 
                        "Status": "Deployed"
                    })
                    st.rerun()

    # --- SHARED VIEW WITH INSTITUTION BRANDING ---
    if display_key and st.session_state.data_store[display_key]:
        st.markdown("---")
        st.subheader(f"📋 Official Records: {nav}")
        
        # Displaying the Data Table
        df_view = pd.DataFrame(st.session_state.data_store[display_key])
        st.dataframe(df_view, use_container_width=True)
        
        c1, c2 = st.columns(2)
        with c1:
            row_to_del = st.selectbox("Select Row to Delete", df_view.index)
            if st.button("🗑️ Remove Entry"):
                st.session_state.data_store[display_key].pop(row_to_del)
                st.rerun()
        with c2:
            # Generate PDF with Institution context
            pdf_bytes = create_pdf(st.session_state.data_store[display_key], nav)
            st.download_button(f"📥 Download {st.session_state.data_store['School_Name']} Report", 
                               pdf_bytes, f"{st.session_state.data_store['School_Name']}_{nav}.pdf")
