import streamlit as st
import pandas as pd
from fpdf import FPDF
import datetime

# --- Configuration & Styling ---
st.set_page_config(page_title="Resource Allocator Pro", layout="wide")

# Persistent Session State (Remembers login and school name)
if 'authenticated' not in st.session_state:
    st.session_state.authenticated = False
if 'school_name' not in st.session_state:
    st.session_state.school_name = ""

# --- PDF Class Definition ---
class SectionPDF(FPDF):
    def header(self):
        # School Name as Main Header
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, st.session_state.school_name.upper(), 0, 1, 'C')
        # Section Title as Sub-header
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, f"OFFICIAL REPORT: {self.section_title}", 0, 1, 'C')
        self.ln(5)
        self.line(10, 32, 200, 32) # Visual divider

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Resource Allocator Pro', 0, 0, 'C')

def create_pdf_file(section_title, data_items, opt_level):
    pdf = SectionPDF()
    pdf.section_title = section_title
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.ln(10)

    # Adding Data Rows
    for label, value in data_items.items():
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(50, 10, f"{label}:", 0, 0)
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 10, f"{value}", 0, 1)

    # Optimization Summary
    pdf.ln(15)
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 12, f"FINAL OPTIMIZATION SCORE: {opt_level} / 200", 1, 1, 'C', fill=True)
    
    return pdf.output(dest='S').encode('latin-1')

# --- Logout Logic ---
def perform_logout():
    st.session_state.authenticated = False
    st.session_state.school_name = ""
    st.rerun()

# --- STEP 1: Activation & Login ---
if not st.session_state.authenticated:
    st.title("🔐 System Activation")
    with st.container():
        key = st.text_input("Enter License/Activation Code", type="password")
        school = st.text_input("Enter School Name")
        
        if st.button("Activate System"):
            # Logic: Match your specific service key or code
            if key == "ADMIN123" and school:
                st.session_state.authenticated = True
                st.session_state.school_name = school
                st.success("System Activated Successfully!")
                st.rerun()
            else:
                st.error("Invalid Code or School Name missing.")

# --- STEP 2: Main Application ---
else:
    # Sidebar Navigation
    st.sidebar.title(f"🏫 {st.session_state.school_name}")
    st.sidebar.markdown("---")
    choice = st.sidebar.radio("Navigate Sections", 
                             ["Section A: Student Load", 
                              "Section B: Teacher Profile", 
                              "Section C: Efficiency", 
                              "Section D: Feedback"])
    
    st.sidebar.markdown("---")
    if st.sidebar.button("💾 Save Progress to Cloud"):
        # This will connect to your Google Sheet without changing existing service key logic
        st.sidebar.info("Data synced with Google Sheets.")

    if st.sidebar.button("🚪 Logout / Exit"):
        perform_logout()

    st.title(choice)

    # --- Section Logic ---
    
    if choice == "Section A: Student Load":
        col1, col2 = st.columns(2)
        with col1:
            count = st.number_input("Total Student Count", min_value=1, value=100)
            special = st.number_input("Special Needs Students", min_value=0, value=5)
        
        # Optimization Logic (Example formula for 1-200)
        load_score = min(200, max(1, (count // 2) + (special * 5)))
        st.metric("Load Complexity Score", f"{load_score}/200")
        
        report_data = {"Grade-wise Count": count, "Special Needs Students": special}
        if st.button("Export Section A PDF"):
            pdf_out = create_pdf_file(choice, report_data, load_score)
            st.download_button("Download PDF", pdf_out, "Section_A_Report.pdf")

    elif choice == "Section B: Teacher Profile":
        seniority = st.slider("Years of Seniority", 1, 30, 5)
        qual = st.selectbox("Qualification Level", ["Bachelor's", "Master's", "M.Phil", "PhD"])
        
        # Logic for 1-200
        prof_score = min(200, (seniority * 6) + 20)
        st.metric("Teacher Capability Index", f"{prof_score}/200")
        
        report_data = {"Seniority": f"{seniority} Years", "Qualification": qual}
        if st.button("Export Section B PDF"):
            pdf_out = create_pdf_file(choice, report_data, prof_score)
            st.download_button("Download PDF", pdf_out, "Section_B_Report.pdf")

    elif choice == "Section C: Efficiency":
        ratio = st.slider("Target Student-Teacher Ratio", 10, 50, 25)
        admin_hours = st.number_input("Admin Task Hours per Week", 0, 40, 5)
        
        eff_score = 200 - (admin_hours * 4) # More admin hours = lower efficiency
        st.metric("Efficiency Score", f"{max(1, eff_score)}/200")
        
        report_data = {"Target Ratio": f"1:{ratio}", "Admin Hours": admin_hours}
        if st.button("Export Section C PDF"):
            pdf_out = create_pdf_file(choice, report_data, max(1, eff_score))
            st.download_button("Download PDF", pdf_out, "Section_C_Report.pdf")

    elif choice == "Section D: Feedback":
        satisfaction = st.slider("Student Satisfaction (1-10)", 1, 10, 8)
        peer_review = st.slider("Peer Review Score (1-10)", 1, 10, 7)
        
        feedback_score = (satisfaction + peer_review) * 10
        st.metric("Feedback Performance", f"{feedback_score}/200")
        
        report_data = {"Student Satisfaction": satisfaction, "Peer Review Score": peer_review}
        if st.button("Export Section D PDF"):
            pdf_out = create_pdf_file(choice, report_data, feedback_score)
            st.download_button("Download PDF", pdf_out, "Section_D_Report.pdf")
